#ifndef LC_TAPDANCE_H_
#define LC_TAPDANCE_H_

// Tab dance
enum {
  TD_MINUS_PLUS,
  TD_QUOT_SCLN,
  TD_SLSH_BSLS,
  TD_COMM_BSLS,
};
tap_dance_action_t tap_dance_actions[] = {
    [TD_MINUS_PLUS] = ACTION_TAP_DANCE_DOUBLE(KC_MINS, KC_PLUS),
    [TD_QUOT_SCLN] = ACTION_TAP_DANCE_DOUBLE(KC_QUOT, KC_SCLN),
    [TD_SLSH_BSLS] = ACTION_TAP_DANCE_DOUBLE(KC_SLASH, KC_BACKSLASH),
    [TD_COMM_BSLS] = ACTION_TAP_DANCE_DOUBLE(KC_COMM, KC_BSLS),
};


#endif // TAPDANCE_H_
